### ISSUE TITLE
Keep action state over midnight

### ISSUE THREAD

**Issue by Kaibob2** [nielsfaber/scheduler-component#167]
### Checklist
- X I checked for similar existing requests (both open and closed) before posting.
- X My request is generic, other users may benefit from it too.

### Proposal
It would be great if, in a scenario like pictured below, if timeslot 2 equals the state of timeslot 0 to virtually gather them into one action. For example in the scenario below it says

![SharedScreenshot2](https://user-images.githubusercontent.com/20832276/148353606-020ecc5a-2a5a-4909-b2db-3ac13cebe053.jpg)

Which translates to: Next action: close, from dusk until 0:00, at 16:43
But in fact it would be: Next action: close, from dusk until **6:30,** at 16:43

![SharedScreenshot](https://user-images.githubusercontent.com/20832276/148352784-d6fd608b-e3fc-41d3-a81c-6077ac8a8221.jpg)

**Comment by nielsfaber** [comment]
Can you please split your request into 2 separate ones?

**Comment by Kaibob2** [comment]
Done :)

**Comment by nielsfaber** [comment]
There is a similar feature requested in https://github.com/nielsfaber/scheduler-component/issues/163

I think it is possible to make scheduler skip the “00:00” point in case the timeslot that follows has the same action.

One problem I see is that, following your example, on Friday afternoon the next task for that schedule will be on Monday morning. I think scheduler should still show “from sunset to 00:00” in this case, since there are no timeslots in the weekend.

Note that dusk is not the same as sunset. Dawn and dusk are not supported (but can be achieved with some offset).

**Comment by Kaibob2** [comment]
I see, but in #163 it's more a trigger issue if i get it right. For me it's more a kind of "What happens next and when" issue.

> One problem I see is that, following your example, on Friday afternoon the next task for that schedule will be on Monday morning. I think scheduler should still show “from sunset to 00:00” in this case, since there are no timeslots in the weekend.

I agree. If there is no timeslot afterwards the schedule ends at midnight by showing “from sunset to 00:00”

Sorry for the confusion, i meant sunset and not dusk. English isn't my first language and it appears there are even a lot more "sun states" than I thought before starting to fiddel around with HA :) For me, the "sunset +/- 2h" is sufficient.

**Comment by Kaibob2** [comment]
I'm would still be very interested in this feature, but thanks for reminding...bot.

**Comment by Kaibob2** [comment]
Is there any progress on this enhancement?

**Comment by nielsfaber** [comment]
There is no progress on this.
The issue is that in the scheduler code the part that deals with the timers is completely isolated from the part which deals with the actions, hence quite some things would need to be reshuffled to add this.
I cannot give a timeline for this.
