### ISSUE TITLE
Scheduler component doesn’t work anymore 

### ISSUE THREAD

**Issue by RVis78** [nielsfaber/scheduler-component#195]
I updated my HA to the latest version. Also all my integrations (incl. HACS) 

For some unknown reason the scheduler component didn’t work anymore. 

—
Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:383 
Integration: Switch (documentation, issues) 
First occurred: 7:31:54 AM (4 occurrences) 
Last logged: 7:41:11 AM

Error adding entities for domain switch with platform scheduler
Error while setting up scheduler platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

I reinstalled, reloaded and restarted the system, but no luck.

**Comment by nielsfaber** [comment]
Please check that you are on v3.2.8.
The error suggests otherwise.

**Comment by RemcoVisser1978** [comment]
I checked the version: 
But on update I only can select v3.2.7.

how to get v3.2.8?

**Comment by nielsfaber** [comment]
3.2.8 should be available via HACS but you can also overwrite the files manually.
I remember I did something wrong with the release causing it not to show up in HACS, see here: https://github.com/nielsfaber/scheduler-component/issues/192.
This should be solved now (perhaps you need to refresh the browser cache), other people confirmed they could select it.

**Comment by RemcoVisser1978** [comment]
I did what you discribed; and did refresh browser cache, but still no luck.

manually updating the files will still left me with version v3.2.7.

I will try later today again.

**Comment by arripeo** [comment]
Same behavior for me, the schedule doesn't work anymore with the updating of hacs, the last version 3.2.8 is not available.
I've tryed to remove than add again the integration. I was able to add the first schedule by the card, but when i tryed to save the card said that the integration was unavailable
HassOS OS 7.6 on raspberry PI4
HA core-2022.4.5
supervisor-2022.04.0
HACS v1.24.5

**Comment by ooktown** [comment]
First of all: the Scheduler component for HA is GREAT. I love the interface and ease of use.

About the problem with the latest version of HA: I couldn't get v3.2.8 to show up, even after clearing the cache for GitHub, so I needed to download the repository and manually install it by unzipping the files, copying and overwriting the files in the custom component directory for scheduler, and restarting HA. I used the terminal function (Linux command line interface) in HA. After restarting HA, my Scheduler cards showed up again in the Lovelace interface.

I think there still might be a problem with the Github version stuck at v3.2.7, even though v3.2.8 is available. Just my 2 cents.

**Comment by Archer36** [comment]
I too can’t seem to get my HACS to show the 3.2.8 version either. Very odd, not sure how others were able to get to work. 

Looking at the GitHub page I see 3.2.8 as a _tag_ but not as a **release**. Maybe that’s why HACS is confused?

**Comment by nielsfaber** [comment]
@RemcoVisser1978 @arripeo @Archer36 
I just removed the original v3.2.8 and made it again from scratch.
Hopefully this will cause it to show up in HACS correctly for everyone.
Could you please try it and let me know?

**Comment by RemcoVisser1978** [comment]
I could get v3.2.8 to show up, after installing it manually, like @ooktown described.

The scheduler cards showed up in Lovelace, I only had to put in all time stamps again!

As far as I can see, there is still a mismatch in the different versions on my HA instance. 
In HACS / information is v3.2.7 displayed, while in Configuration v3.2.8 is installed.

hopefully this will be solved after a upcoming update!

thanks for your help.

**Comment by nielsfaber** [comment]
@RemcoVisser1978 Thank you for confirming. 
> I only had to put in all time stamps again!

What do you mean by this?
Updates should never cause you to lose your schedules. They are stored in a file in the `.storage` directory (together with all other HA storage) so not affected by updates.

**Comment by RemcoVisser1978** [comment]
@nielsfaber for some strange reason I lost all my schedules. The cards did still exist, but I’ve had to configure them again.

HACS doesn’t show v3.2.8.
![C0E68CC6-1F99-4EE5-8D05-9306623F37E5](https://user-images.githubusercontent.com/62797454/163923600-53e24ca2-fba7-46aa-bc06-1f857f88b8fb.png)

**Comment by breiti78** [comment]
V3.2.8 showed up now as available update. Installed the update and the scheduler card is back on lovelace. Thank you for fixing it.

**Comment by Archer36** [comment]
@nielsfaber That did the trick! I can now see 3.2.8 in HACS! Thank you!

**Comment by ooktown** [comment]
Same here! v3.2.8 showed up in HACS. Thank you!

**Comment by RemcoVisser1978** [comment]
I tried again, and ik showed up!

Thanks for your effort!
