### ISSUE TITLE
HoAs update to version 2025.5.0 the conditions of schedules have disappeared

### ISSUE THREAD

**Issue by KlaWol** [nielsfaber/scheduler-component#443]
Hello, 

unfortunately after HoAs update to version 2025.5.0 the conditions of schedules have disappeared / are no longer accessible. In addition, the tags are no longer adjustable

Regards 
Klaus

**Comment by adampetrovic** [comment]
![image](https://github.com/user-attachments/assets/ae84480a-0657-4059-955c-a5413c1f280c)

Also experiencing this issue. Note the configuration items at the top. They aren't clickable which essentially renders the component immutable.

**Comment by rumlak** [comment]
guessing this is a related issue

![Image](https://github.com/user-attachments/assets/b4413941-438a-4b5f-a6a9-8aa43dff7289)

**Comment by CygnusX2112** [comment]
Jumping in here, seeing the same issue after the latest update. Still running HA core 2025.4.4

**Comment by rgnet5** [comment]
The Scheduler Card v3.2.15 update in HACS fixed it for me.  Thanks.

**Comment by PjotrBaas** [comment]
> The Scheduler Card v3.2.15 update in HACS fixed it for me.  Thanks. 

Great, this does the job. HACS didn't automatically install the uodate.

**Comment by hacscred** [comment]
I run 3.38 and 3.2.15 and I can't edit old entries, even after Control+F5 with 2025.5.2, and even restarting.

**Comment by hacscred** [comment]
@nielsfaber Can you fix this major bug? I am using the scheduler-component (3.38) from git and the scheduler-card from HACS.

**Comment by rgnet5** [comment]
> @nielsfaber Can you fix this major bug? I am using the scheduler-component (3.38) from git and the scheduler-card from HACS. 

Have you tried rebooting the whole system?  I am running the same versions and I have full control of old and new schedules.

**Comment by hacscred** [comment]
@rgnet5 Not the whole operating system, but Home Assistant, yes. There's no reason to reboot for things that don't involve hardware.

**Comment by CygnusX2112** [comment]
All of my issues were resolved by fully patching HA and the integration. Rebooting an OS has very little to do with hardware and a lot to do with starting in a fresh state.

**Comment by hacscred** [comment]
My understanding is that I don't need to remove and then add the card from Home Assistant's dashboard, however.

**Comment by rgnet5** [comment]
> @rgnet5 Not the whole operating system, but Home Assistant, yes. There's no reason to reboot for things that don't involve hardware. 

I'm not suggesting it's hardware, but rebooting HAOS (or whatever OS if you're running core for example, will provide a clean baseline start).

**Comment by rgnet5** [comment]
> My understanding is that I don't need to remove and then add the card from Home Assistant's dashboard, however. 

Correct. I just updated normally

**Comment by hacscred** [comment]
I rebooted despite no well written software has ever required a reboot. 

As expected: absolutely no effect. 

This is still broken.

**Comment by hacscred** [comment]
I managed to find a somewhat more useful message:

```
Logger: frontend.js.modern.202505160
Source: components/system_log/__init__.py:331
First occurred: 7:25:31 PM (6 occurrences)
Last logged: 9:28:17 PM

Uncaught error from Firefox 138.0 on Linux Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry 69579/</A.prototype.define (src/scoped-custom-element-registry.ts:180:12) re/</< (/hacsfiles/scheduler-card/scheduler-card.js:29:61) re/< (/hacsfiles/scheduler-card/scheduler-card.js:29:76) t (/hacsfiles/scheduler-card/scheduler-card.js:1:276) /hacsfiles/scheduler-card/scheduler-card.js:261:847 /hacsfiles/scheduler-card/scheduler-card.js:1993:295
Uncaught error from Chrome WebView 136.0.7103.125 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-group" has already been used with this registry A.define (src/scoped-custom-element-registry.ts:180:12) /hacsfiles/scheduler-card/scheduler-card.js:29:61 /hacsfiles/scheduler-card/scheduler-card.js:29:76 t (/hacsfiles/scheduler-card/scheduler-card.js:1:276) /hacsfiles/scheduler-card/scheduler-card.js:261:847 /hacsfiles/scheduler-card/scheduler-card.js:1993:295
```

**Comment by CygnusX2112** [comment]
Have you cleared your browser cache or tried loading in a private tab?

**Comment by hacscred** [comment]
I think I already fixed it. The cause of the above error was two versions of the resources. I don't know yet whether that resolved everything, but that's likely.

**Comment by hacscred** [comment]
Apparently, that was not the root cause, although that error is gone.

**Comment by hacscred** [comment]
Yes, that was it. So, root cause was having duplicate resources with a different prefix. Additionally, "installing" doesn't actually install in all possible cases via HACS. 

Conclusion: there are bugs, but when one only uses HACS there is no bug, so this one can be closed.
