### ISSUE TITLE
Not work properly with workday sensor.

### ISSUE THREAD

**Issue by gsergeysdk** [nielsfaber/scheduler-component#86]
Thanks for the great planner.

I have a light that I want to turn on at different schedule during workdays and non-workdays, including holidays.

I got a sensor for working days:
```
binary_sensor:
  - platform: workday
    country: RUS
    add_holidays:
      - "2020-12-31"
```

January 6 and 7 we have holidays.
State this sensor:
![Screenshot workday](https://user-images.githubusercontent.com/75040714/103865275-01008700-50d5-11eb-9a8a-39c519ab9e48.png)

Add 2 schedules:
![Screenshot sheduller - workday](https://user-images.githubusercontent.com/75040714/103865473-50df4e00-50d5-11eb-93c8-81f76a76dda9.png)
![Screenshot sheduller - not workday](https://user-images.githubusercontent.com/75040714/103865486-55a40200-50d5-11eb-9b25-fbdb8988238b.png)

Today (7 january) at 9:30 the schedule did not triggered :
![Screenshot sheduller history](https://user-images.githubusercontent.com/75040714/103868133-871ecc80-50d9-11eb-9939-6d0c0ef13db9.png)
![Screenshot sheduller history 2](https://user-images.githubusercontent.com/75040714/103868148-8b4aea00-50d9-11eb-82d1-0598c8603971.png)

If the schedule is turned off and on, then at the moment of turning on the trigger will work, and the light will turn on, only in the schedule for non-working days, since now is a holiday.

**Comment by nielsfaber** [comment]
Thanks for reporting this.
I will make a test for this scenario.

**Comment by gsergeysdk** [comment]
It looks like it has something to do with a server restart.
After restarting, it does not work normally, but after manually turning off and turning on the scheduler rule, it starts working fine.

Thanks.

**Comment by ntompson** [comment]
(Bringing this issue across from https://github.com/nielsfaber/scheduler-card/issues/343)

I'm loving the simplicity that this card provides compared to automating time based triggers in yaml, but today I discovered that a public holiday was ignored, even though I have the workday sensor configured and working. It's hard to pin down what's gone wrong, as previous testing during a public holiday worked fine.

First, confirmation that the workday sensor is configured and working (today, Monday 8 March, which is a public holiday in Tasmania).

```yaml
binary_sensor:
  - platform: workday
    country: AU
    province: TAS
    add_holidays:
      # Royal Hobart Regatta
      - '2021-02-08'
      - '2022-02-14'
      - '2023-02-13'
      # Royal Hobart Show
      - '2021-10-21'
      - '2022-10-20'
      - '2023-10-26'
```

Confirming that the sensor detected today as public holiday:

<img width="416" alt="Screen Shot 2021-03-08 at 9 38 58 am" src="https://user-images.githubusercontent.com/32885870/110257449-1e2cd580-7ff2-11eb-97e1-53d2886cc178.png">

But this morning, one of my workday tasks was triggered:

<img width="445" alt="Screen Shot 2021-03-08 at 9 40 35 am" src="https://user-images.githubusercontent.com/32885870/110257502-57654580-7ff2-11eb-8fed-d6612b9b504c.png">

Which is configured as follows:

<img width="508" alt="Screen Shot 2021-03-08 at 9 41 33 am" src="https://user-images.githubusercontent.com/32885870/110257537-795ec800-7ff2-11eb-89c9-e4679cbb2b0f.png">

I also noticed that, in the days leading up to the public holiday, the "next task" secondary info in the main scheduler GUI screen indicated tasks running / not running on the basis that Monday would be a workday, not a public holiday.

Making it more difficult to diagnose, I *think* that as soon as I change something (eg add a task / modify a task), the bug disappears. Perhaps this causes scheduler to reload stuff (I don't know what) and in doing so, reassesses the workday sensor. 

So today, after noticing that the public holiday had been missed, I added a new task configured for workday and it correctly showed that first run would be tomorrow. Not only that, but the *other* existing tasks also showed correct next run times.

It would be great if this can be fixed as I need to be able to rely on workdays being correctly detected - the family don't like to be woken early on a public holiday!!

Thanks for your great work

**Comment by crazyfx1** [comment]
I have the same issue. Today is public holiday and the workday action was executed.

**Comment by nielsfaber** [comment]
In the meantime I discovered this issue myself as well, and I changed the implementation to eliminate the issue.
I am hoping to release an update soon that should fix the issue for everyone.

**Comment by ntompson** [comment]
That's great. 

Unfortunately, I discovered a similar problem over the weekend: we changed out of daylight savings time here in Australia. The behaviour was quite similar. The day before the time change, all of the predicted times for the next day (the first day out of daylight savings) were displaying an hour early and ultimately ran an hour early when they triggered. The following day (the second day out of daylight savings), they ran correctly.

I wonder whether the issue is similar and the fix you've discovered might fix this also.

**Comment by nielsfaber** [comment]
> The day before the time change, all of the predicted times for the next day (the first day out of daylight savings) were displaying an hour early and ultimately ran an hour early when they triggered. 
I wonder whether the issue is similar and the fix you've discovered might fix this also.

Yes.
In fact, the DST change was 2 weeks ago where I live. On the night before, I prepared various test-timers to see which method would take into account the time shift, and which wouldn't (unfortunately I really had no clue beforehand, as the timers are handled by HA functions, and documentation is non-existent).
Based on this test result I made changes to the code.

**Comment by nielsfaber** [comment]
FYI: I made a beta release today for the scheduler-component, which should take care of issues with the workday sensor as well as DST changes.

**Comment by nielsfaber** [comment]
I just released v3.1.0 which should fix problems with workday sensor and holidays.

**Comment by Plawasan** [comment]
Thanks for this update, it will definitely simplify my setup. Just to be clear that I understand the logic fully:

- I have a workday sensor configured for my region
- I have a schedule configured to run on workdays - for that I have "workdays" selected (duh..)
- Second schedule is only supposed to trigger on weekends and holidays - for that I have "weekend" selected but I'm not clear on whether this will run on holidays that fall on a workday.

So the only thing I wanted to confirm is that "weekend" actually means "non-workdays" i.e. weekends AND holidays, correct?

Thanks!

**Comment by nielsfaber** [comment]
> So the only thing I wanted to confirm is that "weekend" actually means "non-workdays" i.e. weekends AND holidays, correct?

Yes.
I assumed that most people would like to separate workdays vs non-workdays.
Between non-workdays there's not really a separation weekend vs holidays in the scheduler (unless you choose sat+sun).

**Comment by Plawasan** [comment]
Yes, that is exactly the behavior I would expect so good to hear that is indeed the case. Thanks again.

**Comment by rousveiga** [comment]
Hello. I have just updated to 3.1.2 and the issue persists for me. I've set today as a custom holiday, and the workday sensor identifies it correctly, but my schedules for workdays still ran today.

**Comment by nielsfaber** [comment]
@rousveiga I did some testing and found a typo in my code which specifically affects the holiday cases.
It can be fixed by changing this: https://github.com/nielsfaber/scheduler-component/commit/928ff56422195d26e336d15f0d06fe969b426896
I will include it in the next release of the scheduler-component.

**Comment by rousveiga** [comment]
@nielsfaber That worked, thank you!

**Comment by nielsfaber** [comment]
Problem should be solved in v3.3.3. Closing issue.
